### ISSUE TITLE
dns issue after uninstall

### ISSUE THREAD

**Issue by mdzare** [0xNeu/Rainb0w-Lite#2]
بعد از اینکه از سرور حذف میکنیم، دیگه dns کار نمیکنه. به صورتی که نه میشه از گیتهاب چیز دیگه ای نصب کرد نه همون سرویس هایی که روی سرور است دیگه کار میکنه
در واقع فایل resov.config را پاک میکند.

**Comment by ghost** [comment]
پس از لغو نصب، فایل resolv.conf فعلی حذف و با فایل نمونه ی اصلی از مسیر /run/systemd/resolve/resolv.conf جایگزین میشه اگر با این وجود همچنان مشکل دارید، دستورات زیر رو اجرا کنید یک به یک:

```
echo "DNS=1.1.1.1" | tee /etc/systemd/resolved.conf
ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
systemctl restart systemd-resolved
```
